### ISSUE TITLE
Java and C file running remotely

### ISSUE THREAD

**Issue by avltree9798** [thebaselab/codeapp#186]
Hi,

Just update the app to the latest version but somehow C and Java file are running remotely.

![IMG_0021](https://user-images.githubusercontent.com/16130362/125104425-92de6080-e107-11eb-91ad-55dc2dff1ab3.png)

OS Version: iPadOS 15 Beta 2
App Version: 1.2.5

**Comment by bummoblizard** [comment]
Hey. Remote C compilers are brought back due to a request. Since it was the default option in previous versions, they were enabled from the settings menu. Therefore, you can simply disabled them in the settings menu.

For Java, I am still working on porting JDK to iOS. So only remote execution is available.
