### ISSUE TITLE
Cannot stage changes as repository doesn’t exist

### ISSUE THREAD

**Issue by wtpalexander** [thebaselab/codeapp#195]
I don’t seem to be able to stage any changes for this repo that I’ve cloned, a pop up error says the repository doesn’t exist. I’m not so sure how this could be so since I’m looking at the repository?

I’m using an 2021 iPad Pro running iOS 14.6 

![6D616D0D-F1A6-4C84-86BE-3C76346FF281](https://user-images.githubusercontent.com/7461082/125849973-1d3bea2b-7e14-4ab8-8225-3d18c2d67dfa.jpeg)

**Comment by bummoblizard** [comment]
Thank you for opening an issue, here are some workarounds you could try.

- Tap the refresh button in the explorer.

- Try using the git command in terminal and see if it works. Type `git add HomeView.swift` in terminal.

It would be great if you can provide me with an example repository to demonstrate this, since I can't reproduce this on my own device.

**Comment by wtpalexander** [comment]
Thanks for the quick reply. I’ve attempted both the workaround methods but to no avail. Using terminal just yields a `HomeView.swift does not exist`. I wonder if its anything to do with where my repo is stored locally on my iPad? Where do you recommend storing these files. When I first downloaded the app I cloned a repo and it stored in the App’s specific documents folder, I then struggled to clone another project so ended up creating a new folder on my iPad storage (“On my iPad” in Files), I could then open this folder and clone the repo in? However the git operation work in the first repo and not the second? How could I clone the second project into the App’s specific documents as well?

**Comment by bummoblizard** [comment]
In Code App, there's a concept of workplace folder. It's essentially the root folder of the editor where the built-in source control would try to locate the repository. When you clone a repository, the repository does not automatically become the root folder, you'll need to press the Open Folder button to do so. You can also long press a folder cell to reveal the Assign as workplace folder option.

If the git command inside terminal yields `<file> not found`, it's probably due to the fact that you are inside the wrong working directory. Try to `cd` into the directory that your file is located first.

**Comment by wtpalexander** [comment]
Thanks @bummoblizard, setting the working directory in the terminal explicitly works! Is there a way to reset the source control tab so that I can clone another directory when I’m in the root ‘Documents’ folder?

**Comment by bummoblizard** [comment]
> Thanks @bummoblizard, setting the working directory in the terminal explicitly works! Is there a way to reset the source control tab so that I can clone another directory when I’m in the root ‘Documents’ folder?
> 
> 
> 
> 

You'll need to delete the `.git` folder located there. You can either do `rm -rf .git` or head over to settings and enable show hidden file, then you can delete the folder in the GUI. Also refresh the file explorer if needed.
