### ISSUE TITLE
Code App is now open source!

### ISSUE THREAD

**Issue by bummoblizard** [thebaselab/codeapp#200]
I'm proud to announce that Code App is now open source. The source code is now available on this repository under the [MIT License](https://en.wikipedia.org/wiki/MIT_License).

### Why?
Software development on iOS / iPadOS has always been a pain in the ass. Due the sandboxed environment and other system limitations, you'll often need to rely on a limited number of proprietary apps that are either not actively maintained or provided with very limited features. It was also difficult to port existing tools to iOS due to the differences in the platform. 

This made developer tools on iOS a very niche market. For most developers, it wasn't even worth it to develop such tools because of the limited market. See https://panic.com/blog/the-future-of-code-editor/.

The situation somewhat changed with the [ios-system](https://github.com/holzschu/ios_system) project. It is a framework that provide the basis to port Unix utilities to iOS and many great works like [Pyto](https://github.com/ColdGrub1384/Pyto) and [a-Shell](https://github.com/holzschu/a-shell) have derived from it.

In addition, the performance of Safari on iOS has been improved a lot over the years and allowed us to use the core editor of [VS Code](https://microsoft.github.io/monaco-editor/) directly. This provide desktop-equivalent TextMate based syntax highlighting, as well as powerful APIs that can be used to integrate IDE features easily, for example Language Server Protocols (https://github.com/TypeFox/monaco-languageclient).

By open sourcing Code App, we could help building a healthier community around software developer tools on iOS. And hopefully development on tablet or phone will become much more commonplace.

### Contribution
Contribution is welcomed. Since I knew very little in iOS or software development in general back when I started this project, many of the code could be poorly documented or written. 😀

**Comment by Lukas-Batema** [comment]
I do have a sad reality about this. Open source projects like: [code-server](https://github.com/cdr/deploy-code-server/), are probably going to dominate the market on non-local PC/Mac editors, since it is (no offence), way better developed, has been open source for a while, and already has a community developed that is contributing to the project to make it better. Now I am not saying that, that alone will kill mobile Text Editors/Terminals, but now that GitHub has started developing codespaces, which is related to the project I mentioned earlier, although you most likely will have to have a GitHub Pro account or organisation to use the feature, it will still take the attention and user-base away from these types of editora, like Code App. If you don’t think of features that directly align with these dominating projects, this community and mobile text editing software, will die. I would suggest updating the UI, like: adding more themes, adding a marketplace that allows Code App users to submit their created extensions for this app specifically, to be added to this app. Maybe you could add file templates that can also be locally added to the user’s template section in the sidebar, along with the original ones, plus you should probably update the formatting on the already implemented templates. I noticed that the doctype in the HTML template is not correctly capitalised. Lastly, I would recommend you push out the git capability features, ASAP. Sorry if this didn't sound  like constructive feedback, but I do hope this helped! I do recall, awhile back, if I recall, in late-february, that I suggested for someone knowledgeable in Swift, to help with the development of this app, or to make it open-source. Good luck, and I will still be using this app as long as this community thrives!

**Comment by bummoblizard** [comment]
> I do have a sad reality about this. Open source projects like: [code-server](https://github.com/cdr/deploy-code-server/), are probably going to dominate the market on non-local PC/Mac editors, since it is (no offence), way better developed, has been open source for a while, and already has a community developed that is contributing to the project to make it better. Now I am not saying that, that alone will kill mobile Text Editors/Terminals, but now that GitHub has started developing codespaces, which is related to the project I mentioned earlier, although you most likely will have to have a GitHub Pro account or organisation to use the feature, it will still take the attention and user-base away from these types of editora, like Code App. If you don’t think of features that directly align with these dominating projects, this community and mobile text editing software, will die. I would suggest updating the UI, like: adding more themes, adding a marketplace that allows Code App users to submit their created extensions for this app specifically, to be added to this app. Maybe you could add file templates that can also be locally added to the user’s template section in the sidebar, along with the original ones, plus you should probably update the formatting on the already implemented templates. I noticed that the doctype in the HTML template is not correctly capitalised. Lastly, I would recommend you push out the git capability features, ASAP. Sorry if this didn't sound  like constructive feedback, but I do hope this helped! I do recall, awhile back, if I recall, in late-february, that I suggested for someone knowledgeable in Swift, to help with the development of this app, or to make it open-source. Good luck, and I will still be using this app as long as this community thrives! 

Thanks for the suggestions, I'll definitely be adding some of the features you mentioned. 

GH Codespace and other similar products such as gitpod are undoubtedly superior and better suited for actual development. But I can think of a few reasons why Code App still has its value:

- No subscription
- Complete offline support
- Robust local file support
- Way faster startup time
- Other native capabilities
- Everything is open source

Now that it's open source, you can just fork it and add features that you want. For example, adding VSCode compatible themes files in `Library/themes` should allow the app to load extra themes.

**Comment by DaneHoffman** [comment]
@Lukas-Batema IMO, offline code editors are important for mobile devices because of the increased stability they provide. There is a niche for this app on that basis alone. Code-server is good for people who have cellular radios and an internet-facing VPS, but for everyone else, development of apps like this one are important. And even though I have both of those things and a working code-server installation, I still find myself using this app more often because it's not subject to network drops like code-server.

**Comment by Lukas-Batema** [comment]
> @Lukas-Batema IMO, offline code editors are important for mobile devices because of the increased stability they provide. There is a niche for this app on that basis alone. Code-server is good for people who have cellular radios and an internet-facing VPS, but for everyone else, development of apps like this one are important. And even though I have both of those things and a working code-server installation, I still find myself using this app more often because it's not subject to network drops like code-server.

I agree, just was warning and suggesting :)
