### ISSUE TITLE
Swift Device Simulation

### ISSUE THREAD

**Issue by Lukas-Batema** [thebaselab/codeapp#215]
It would be very helpful if we could simulate an iPhone on an iPhone device, or an iPad/iPhone on an iPad device. This may help some contribute to this repo, as well as me, since I cannot re-download X-Code, since my iMac is stuck at a later Catalina Update. Thank you!
___
**EDIT:** *If there is a way to re-download an older version of X-Code, without having to purchase a whole new iMac, please help me! Thanks again!*

**Comment by bummoblizard** [comment]
You can download previous versions of Xcode here under 'Additional Downloads': https://developer.apple.com/xcode/resources/

For simulation, do you mean in the app? It's likely not feasible at all since it basically needs a port of Xcode to iOS. The closest thing you'll get is Apple's Swift Playground.

**Comment by Lukas-Batema** [comment]
> You can download previous versions of Xcode here under 'Additional Downloads': https://developer.apple.com/xcode/resources/
> 
> 
> 
> For simulation, do you mean integrating an iOS simulator in the app? It's likely not feasible at all since it basically needs a port of Xcode to iOS. The closest thing you'll get is Apple's Swift Playground. 
> 
> 

Ohhh. Okay, thanks!
