### ISSUE TITLE
Push repo bug

### ISSUE THREAD

**Issue by louka-dubois** [thebaselab/codeapp#331]
When I want tu push something into my **public** repo, I have an alert saying: **_too many redirects or authentication replays_**
I’m on iPad Pro, iOS 15 and using the latest update

**Comment by bummoblizard** [comment]
Hi. Even for public repos, you'll need authentication to push changes to them.

See https://github.com/thebaselab/codeapp/wiki/FAQ#q-i-cant-clone-a-private-repository-or-push-changes-to-my-repository

Q: I can't clone a private repository or push changes to my repository

A: You'll need to set your credentials at Settings > Version Control > Authentication. In many cases, you need to use a personal access token instead of the regular password. For GitHub, see https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by louka-dubois** [comment]
Oh yes thanks I just tried with the token and it worked!
