### ISSUE TITLE
Bugs with applying custom tab size on new scripts.

### ISSUE THREAD

**Issue by YZ6565785** [thebaselab/codeapp#71]
The settings for indentation does not save properly. It always uses the default size (4).

It does show the tab size has been changed in settings, but it has inconsistent result in the editor.

It is quite annoying to re-set the tab size every time creating a new script.

**Comment by Lukas-Batema** [comment]
> The settings for indentation does not save properly. It always uses the default size (4).
> 
> 
> 
> It does show the tab size has been changed in settings, but it has inconsistent result in the editor.
> 
> 
> 
> It is quite annoying to re-set the tab size every time creating a new script.

My app does not do that, can you explain a bit more on how I can reproduce it? Thank you!

**Comment by bummoblizard** [comment]
Hi, the editor detects the tab sizes in existing code and that value overrides the user settings. For example, if you imported a script with tab sizes of 2, the editor will uses 2 as the tab size instead of the user supplied value. On the other hand, if you created a new file from scratch, it will use the user-supplied setting.

In your case, I think it would be feasible to add a convert tab size function, like VS Code does.

**Comment by YZ6565785** [comment]
Thanks, I see.👍🏻 Because the template script always has tab size 4.
