### ISSUE TITLE
Editor Not Ready - iPad Lockdown Mode

### ISSUE THREAD

**Issue by ais-developer** [thebaselab/codeapp#895]
The editor will not open while iPad is in Lockdown Mode, infact I've even had to enable developer mode to get the editor to work correctly. I have security concerns so I must enable Lockdown mode with developer mode off. Please help fix this. Thank you so much!

**Comment by bummoblizard** [comment]
Thanks for the heads up. I will investigate this.

**Comment by bummoblizard** [comment]
This is likely due to JIT not being available in lockdown mode, which the syntax highlighting engine requires. While I am looking for workarounds to this, you might consider disabling lockdown mode for Code App (on a per app basis).

<img width="322" alt="image" src="https://github.com/thebaselab/codeapp/assets/38398443/0e35974b-5540-4614-93f5-188622cd47c3">

**Comment by bummoblizard** [comment]
Fixed by disabling syntax highlighting when WebAssembly is not supported. This change will be available on TestFlight soon.

**Comment by ais-developer** [comment]
Would it be possible to please add me to TestFlight as a tester. I would love to have access to these features and perhaps provide feedback and additional testing results (free of charge of course lol)

**Comment by bummoblizard** [comment]
> Would it be possible to please add me to TestFlight as a tester. I would love to have access to these features and perhaps provide feedback and additional testing results (free of charge of course lol)

Here's the link: https://testflight.apple.com/join/EgZ8sE2P. But the review for the latest version is taking longer than expected so the feature is not available there yet. If you would like to try it now, you can build the app yourself.
