### ISSUE TITLE
Sug: Ability to select the code

### ISSUE THREAD

**Issue by antic-sar** [thebaselab/codeapp#949]
When trying to hold the text for sometime to enable the selection option it is not working fully. It just shows like in image and we cannot select with dragging the knob.

Would be very helpful if this can supported. 

<img width="309" alt="image" src="https://github.com/thebaselab/codeapp/assets/68851158/3dd1c6e1-4604-477b-adf0-572882832b9b">

**Comment by mateus3c** [comment]
yeah, that’s a super basic feature and i have NO idea why it isn’t in the app yet. we pay for a coder editor that is worst than the free ones? that’s ridiculous, the dev should take a look at those important features instead of trying to make the app appearance look like VS Code. ATM i recommend use the ‘Coder Editor’ app, it’s free, it has a nice interface and works the same as Code App but with some extra functionalities, like this one.

**Comment by adamszigeti** [comment]
#958 is related I believe. It's happening to me as well, it would be nice to get a fix for this.

**Comment by mateus3c** [comment]
@thebaselab

**Comment by bummoblizard** [comment]
1.8.0 added support for Runestone editor mode which allows native text selection.

See https://code.thebaselab.com/guides/getting-familiar#switching-between-monaco-editor-and-runestone-editor.
